### ISSUE TITLE
Model output contents, which one did you use for downstream tasks?

### ISSUE THREAD

**Issue by GeorgeBatch** [HistAI/hibou#4]
Dear authors,

Thank you for releasing the code and the weights!

I have questions regarding the model output. For both the `hibou-b` and `hibou-L` versions, the outputs are the same except for the feature dimension: 768 for `-b` and 1024 for `-L`.

The output has two parts: `pooler_output` and `last_hidden_state`.

**Q1: Is this how the dimensions are made up?**

- pooler_output [batch_size, 768]
- last_hidden_state [batch_size, 261, 768]
    - batch_size images
    - 261 tokens = 1 cls token + 4 DINOv2 register tokens + 256 (16*16) patch tokens
    - 768 features
    
**Q2: Which feature vector do you use for downstream tasks? `output.pooler_output` or `output.last_hidden_state[:, 0 :]` ?**

Many thanks,
George Batchkala

**Comment by GeorgeBatch** [comment]
I checked on a sample image, `output.pooler_output` and `output.last_hidden_state[:, 0 :]` are the same. Did you get `pooler_output` as a separate thing for convenience?

**Comment by megavaz** [comment]
Hello, sorry for the long response. Yes `output.pooler_output` and `output.last_hidden_state[:, 0, :]` are the same thing. We usually use `output.pooler_output` for classification tasks. But you can test another approach `output.last_hidden_state[:, 5:, :].mean(dim=1)`. This way you'll get the same dimensions but you'll get patch embeddings instead of cls embedding. They might yield a different result on your downstream tasks (worse, or better, or actually the same).

**Comment by GeorgeBatch** [comment]
@megavaz, makes sense, thanks! Would you ever use the 4 register tokens for downstream tasks?

**Comment by megavaz** [comment]
Tbh I wouldn't, since it's impossible to know what they store. Their primary goal is to sort of store some internal info that the model uses somehow. You can check [the paper](https://arxiv.org/abs/2309.16588) about registers.
